build(package.json): update icon version
primefaces/primevue pull request #3044
Opened 2022-09-29 09:34 UTC by Valar103769

###Defect Fixes
When submitting a PR, please also create an issue documenting the error.

###Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.

2022-10-14 12:39 UTC, jnoordsij requested changes

2022-10-14 12:39 UTC, jnoordsij commented on package-build.json
> +      "primeicons": "6.0.1"
This should probably be `"^6.0.0"` or `"^5.0.0 || ^6.0.0"` (or `5 - 6`)? Else it will require this very specific version.

2022-10-19 19:07 UTC, jnoordsij approved these changes

2022-10-20 00:04 UTC, merged

2022-10-20 00:05 UTC, mertsincan commented
Good catch! Thanks a lot for your contribution!

2022-10-24 21:03 UTC, loneil commented
Thanks for this! Was driving me crazy.