Improve datatable performance
primefaces/primevue pull request #4008
Opened 2023-05-31 06:20 UTC by andrewguy

###Defect Fixes
Helps fix https://github.com/primefaces/primevue/issues/4007

This PR does 2 main things to help improve filtering and sorting performance for DataTables:

- Within the `sortSingle` function, performing calls to `resolveFieldData(data1, this.d_sortField)` only once for each item in the dataset, and using a `Map` for later lookups.
- Within the `filter` function, only run filters whose `value` is not `null`.

2023-06-10 14:00 UTC, NeluQi commented
+1

2023-08-12 12:13 UTC, melloware commented
Thank you for these hints I applied the same fixes to PrimeReact: https://github.com/primefaces/primereact/pull/4769

2023-08-17 09:58 UTC, tugcekucukoglu requested changes
`lookupMap` is not a function.

Could you replace it with `lookupMap.get()`

2023-08-18 08:17 UTC, tugcekucukoglu approved these changes

2023-08-18 08:18 UTC, merged