fix: fix top and left styles of the container by subtracting the marg…
primefaces/primevue pull request #4252
Opened 2023-08-09 21:01 UTC by Dmytro-Lukashenko

Unexpected behavior of the ConfirmDialog component during the dragging process:https://github.com/primefaces/primevue/issues/4251

2023-08-10 15:39 UTC, Dmytro-Lukashenko commented
Hi @tugcekucukoglu. The main problem is in the Dialog component logic. But other components that extend Dialog have the same problem.

2023-08-12 07:32 UTC, Dmytro-Lukashenko commented
Hi @cagataycivici, @tugcekucukoglu, @mertsincan, @bahadirsofuoglu, @yigitfindikli, @Merve7, @onursenture, @atakantepe. Guys, could you please check out this bug? We use the amazing Primevue library in our project and we need to fix it. Thanks. Happy coding!

2023-08-12 12:08 UTC, Dmytro-Lukashenko commented
This issue linked to the fixes for Prime,Ng and PrimeReact

primefaces/primeng#13493

primefaces/primereact#4759

2023-08-14 11:39 UTC, melloware requested changes

2023-08-14 11:39 UTC, melloware commented on components/lib/dialog/Dialog.vue
>                          this.lastPageX = event.pageX;
You missed a spot in the Else clause if `keepInViewPort` is false. See my PrimeReact PR.

2023-08-14 12:22 UTC, melloware approved these changes

2023-08-15 09:00 UTC, Dmytro-Lukashenko commented
Hi @melloware. Could you please merge this PR?

2023-08-15 10:49 UTC, merged

2023-08-15 10:49 UTC, mertsincan commented
Thanks a lot for your contribution!

Best Regards,