Update Splitter.vue
primefaces/primevue pull request #4800
Opened 2023-11-10 13:11 UTC by Rakasch

check for data integrity before saving

###Defect Fixes
fixes #4797

2023-11-10 13:33 UTC, melloware requested changes

2023-11-10 13:33 UTC, melloware commented on components/lib/splitter/Splitter.vue
> +            if(Array.isArray(this.panelSizes)) {
```suggestion
            if(ObjectUtils.isArray(this.panelSizes)) {                
```

2023-11-10 23:35 UTC, melloware approved these changes

2023-11-11 15:12 UTC, SoyDiego approved these changes

2023-11-15 08:31 UTC, merged