Feat(DataTable): added showHeaders prop to datatable
primefaces/primevue pull request #5950
Opened 2024-06-22 19:20 UTC by karpov159

###Defect Fixes
This PR adds property showHeaders to DataTable
###Feature Requests
#5949

2024-06-24 09:50 UTC, antlionguard requested changes

2024-06-24 09:50 UTC, antlionguard commented on packages/primevue/src/datatable/DataTable.d.ts
you should put showHeaders description to top of showHeader key. and you put the code between the grid's description and itself, you should fix that too.

2024-06-26 10:30 UTC, antlionguard approved these changes

2024-09-24 06:07 UTC, tugcekucukoglu approved these changes

2024-09-24 06:07 UTC, merged